# Generated by Django 3.2.8 on 2021-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_alter_fileuploadmodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextReflectorModel',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
